title: "Maud Mégret"
description: "Page professionnelle — CV, publications et projets"
theme: jekyll-theme-minimal

# Liens sociaux (facultatifs)
github_username: maud-megret
linkedin: "https://www.linkedin.com/in/ton-lien-linkedin"
email: "maud.megret@lsce.ipsl.fr"

# (Facultatif) Favicon, logo ou photo
logo: /assets/193120(1).jpg

# (Optionnel) Si tu veux que ton site ait un menu
show_downloads: false
